### ISSUE TITLE
🍆

### ISSUE THREAD

**Issue by meowy** [ihaveamac/testing#1]
:eggplant:

**Comment by ihaveamac** [comment]
http://knowyourmeme.com/memes/eggplant-emoji

**Comment by meowy** [comment]
thank you

**Comment by ihaveamac** [comment]
why are we doing this

**Comment by meowy** [comment]
memes

**Comment by meowy** [comment]
we can chat on github now

**Comment by meowy** [comment]
github > skype

**Comment by ihaveamac** [comment]
seems less efficient

**Comment by meowy** [comment]
eh, it works, you even get embeds and stuff

**Comment by meowy** [comment]
github chat bots when

**Comment by ihaveamac** [comment]
kind of pointless when this will all disappear whenever I delete this repo

**Comment by meowy** [comment]
fuck

**Comment by meowy** [comment]
hey this is better than most services tho

**Comment by meowy** [comment]
self-deleting conversations

**Comment by meowy** [comment]
get on this fucking level @snapchat

**Comment by ihaveamac** [comment]
sure……..

**Comment by meowy** [comment]
hacker news: github is the new snapchat

**Comment by ihaveamac** [comment]
this still isn’t a chat client though

**Comment by meowy** [comment]
well you're using e-mail

**Comment by meowy** [comment]
just type in the comment field

**Comment by meowy** [comment]
ctrl-enter

**Comment by meowy** [comment]
done

**Comment by ihaveamac** [comment]
I know but if we’re going to use that why don’t we just email each other

**Comment by meowy** [comment]
why use e-mail when you could just type in web

**Comment by meowy** [comment]
fhuefhuefhue

**Comment by ihaveamac** [comment]
because everyone will read this

**Comment by meowy** [comment]
it's private i swear

**Comment by meowy** [comment]
new york times: github chat logs leaked, 302,140 users affected

**Comment by meowy** [comment]
#1

**Comment by meowy** [comment]
professional software development starts here

**Comment by ihaveamac** [comment]
by shitposting on a test repo

**Comment by meowy** [comment]
:hankey:

**Comment by meowy** [comment]
shitposting at the speed of souuuuund

**Comment by ihaveamac** [comment]
UGHHHHHHHHhhhh

**Comment by meowy** [comment]
:egg: :plant: :egg: :plant: :egg: :plant: :egg: :plant: :egg: :plant: :egg: :plant:

**Comment by ihaveamac** [comment]
I know what I can do here

**Comment by meowy** [comment]
NOTFIXED

**Comment by ihaveamac** [comment]
now it's my own little hole
